from fastapi import APIRouter, HTTPException, BackgroundTasks
from pydantic import BaseModel
from typing import List, Optional, Dict, Any
import os
from dotenv import load_dotenv
import json
import asyncio
from groq import Groq

load_dotenv()

router = APIRouter()

# Initialize Groq client
groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))

class BookSummaryRequest(BaseModel):
    title: str
    author: Optional[str] = None
    isbn: Optional[str] = None
    description: Optional[str] = None

class SummaryResponse(BaseModel):
    title: str
    author: Optional[str] = None
    overview: str
    chapter_breakdown: List[Dict[str, Any]]
    themes: List[str]
    characters: List[Dict[str, Any]]
    quotes: List[Dict[str, str]]
    key_terms: List[Dict[str, str]]
    discussion_questions: List[Dict[str, str]]
    visualizations: Dict[str, Any]

@router.post("/generate", response_model=SummaryResponse)
async def generate_book_summary(request: BookSummaryRequest):
    """
    Generate comprehensive book summary with analysis
    """
    try:
        # Prepare prompt for Groq
        prompt = f"""
        Generate a comprehensive analysis for the book "{request.title}" by {request.author or 'Unknown Author'}.
        
        Book Description: {request.description or 'No description provided'}
        
        Please provide:
        1. A detailed overview (2-3 paragraphs)
        2. Chapter-wise breakdown (5-8 chapters with summaries)
        3. Major themes (5-7 themes)
        4. Main characters (3-5 characters with descriptions)
        5. Important quotes (10 quotes with context)
        6. Key terms and definitions (8-12 terms)
        7. Discussion questions (10-15 questions with sample answers)
        8. Visualization data suggestions for:
           - Character relationship network
           - Timeline of events
           - Theme importance radar chart
           - Sentiment analysis arc
           - Geographic map of story locations
        
        Format the response as JSON with the following structure:
        {{
            "overview": "string",
            "chapter_breakdown": [{{"chapter": "string", "summary": "string"}}],
            "themes": ["string"],
            "characters": [{{"name": "string", "description": "string", "importance": "string"}}],
            "quotes": [{{"quote": "string", "context": "string", "chapter": "string"}}],
            "key_terms": [{{"term": "string", "definition": "string", "importance": "string"}}],
            "discussion_questions": [{{"question": "string", "sample_answer": "string"}}],
            "visualization_suggestions": {{
                "character_network": "description of nodes and edges",
                "timeline": "list of key events with approximate timing",
                "theme_radar": "list of themes for radar chart",
                "sentiment_arc": "description of emotional journey",
                "geographic_map": "list of important locations"
            }}
        }}
        
        Ensure the response is valid JSON only.
        """
        
        # Call Groq API
        chat_completion = groq_client.chat.completions.create(
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            model="llama3-8b-8192",  # Using Llama 3 8B on Groq
            temperature=0.7,
            max_tokens=4000,
            top_p=1,
            stream=False
        )
        
        # Extract and parse the response
        response_text = chat_completion.choices[0].message.content
        
        # Try to extract JSON from the response
        try:
            # Find JSON-like content
            start_idx = response_text.find('{')
            end_idx = response_text.rfind('}') + 1
            if start_idx != -1 and end_idx != 0:
                json_str = response_text[start_idx:end_idx]
                summary_data = json.loads(json_str)
            else:
                # Fallback: create structured response from text
                summary_data = {
                    "overview": response_text[:500] + "..." if len(response_text) > 500 else response_text,
                    "chapter_breakdown": [{"chapter": "Full Book", "summary": response_text[:300] + "..."}],
                    "themes": ["Analysis via Groq LLM"],
                    "characters": [{"name": "Various", "description": "See overview", "importance": "N/A"}],
                    "quotes": [{"quote": "See full analysis", "context": "Generated by AI", "chapter": "N/A"}],
                    "key_terms": [{"term": "Literary Analysis", "definition": "AI-generated insights", "importance": "High"}],
                    "discussion_questions": [{"question": "What are the main themes?", "sample_answer": "See overview section"}],
                    "visualization_suggestions": {
                        "character_network": "Character relationship map based on interactions",
                        "timeline": "Chronological sequence of major plot events",
                        "theme_radar": "Themes identified in the analysis",
                        "sentiment_arc": "Emotional journey throughout the narrative",
                        "geographic_map": "Locations mentioned in the story"
                    }
                }
        except json.JSONDecodeError:
            # If JSON parsing fails, create a structured fallback
            summary_data = {
                "overview": response_text[:800] + "..." if len(response_text) > 800 else response_text,
                "chapter_breakdown": [{"chapter": "Complete Analysis", "summary": "See full response"}],
                "themes": ["Literary Analysis"],
                "characters": [],
                "quotes": [],
                "key_terms": [],
                "discussion_questions": [],
                "visualization_suggestions": {
                    "character_network": "To be implemented",
                    "timeline": "To be implemented",
                    "theme_radar": [],
                    "sentiment_arc": "To be implemented",
                    "geographic_map": []
                }
            }
        
        # Prepare final response
        response = SummaryResponse(
            title=request.title,
            author=request.author,
            overview=summary_data.get("overview", "Overview not available"),
            chapter_breakdown=summary_data.get("chapter_breakdown", []),
            themes=summary_data.get("themes", []),
            characters=summary_data.get("characters", []),
            quotes=summary_data.get("quotes", []),
            key_terms=summary_data.get("key_terms", []),
            discussion_questions=summary_data.get("discussion_questions", []),
            visualizations=summary_data.get("visualization_suggestions", {})
        )
        
        return response
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error generating summary: {str(e)}")

@router.get("/{summary_id}")
async def get_summary(summary_id: str):
    """
    Retrieve a previously generated summary (placeholder for future DB implementation)
    """
    # This would connect to a database in a full implementation
    raise HTTPException(status_code=501, detail="Not implemented - summary retrieval from DB")
